FROM php:7.4-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxslt1-dev \
        libzip-dev \
        libicu-dev \
        libxml2-dev \
        libwebp-dev \
        libjpeg-dev \
        libxpm4 \
        libgd-dev \
        libgmp-dev \
        libbz2-dev \
        libexif-dev \
        libpq-dev \
        libonig-dev \
        libssl-dev \
        libmcrypt-dev \
        libpspell-dev \
        libedit-dev \
        libreadline-dev \
        libsnmp-dev \
        snmp \
        gettext \
        libtidy-dev \
        libldb-dev \
        libldap2-dev \
        libc-client-dev \
        libkrb5-dev \
        libmagickwand-dev \
        imagemagick \
        ghostscript \
        mariadb-client \
        git \
        unzip \
        wget \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install -j$(nproc) \
        bcmath \
        bz2 \
        calendar \
        exif \
        gd \
        gettext \
        gmp \
        intl \
        ldap \
        mysqli \
        opcache \
        pdo_mysql \
        pspell \
        shmop \
        snmp \
        soap \
        sockets \
        sysvmsg \
        sysvsem \
        sysvshm \
        tidy \
        xmlrpc \
        xsl \
        zip \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /var/www/html

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set permissions
RUN chown -R www-data:www-data /var/www

# Copy existing application directory contents
COPY . /var/www/html

# Copy existing application directory permissions
COPY --chown=www-data:www-data . /var/www/html

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]